[build]
  base = "barberapp-web-master"
  command = "npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18"
  NODE_OPTIONS = "--openssl-legacy-provider"
  CI = "false"
  REACT_APP_API_URL = "http://localhost:3001"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200